# Generated by Django 2.2.4 on 2019-08-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoelements',
            old_name='todo_text',
            new_name='text',
        ),
    ]
